{% set name = "orange-widget-base" %}
{% set version = "4.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 088fac5951e502321b435e30a4d65d2d88b37534a4d858213cebd8f8876db474

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - trubar >=0.3.3
    - wheel
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - pyqtgraph
    - anyqt >=0.1.0
    - orange-canvas-core >=0.2.0,<0.3a
    - typing_extensions >=3.7.4.3
    - importlib_resources
    # appnope is skipped here since if we add it package is not noarch: python anymore
    # and appnope is used just optionally in tests

test:
  requires:
    - python {{ python_min }}
  imports:
    - orangewidget.widget
    - orangewidget.gui

about:
  home: https://github.com/biolab/orange-widget-base
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Base Widget for Orange Canvas

  description: |
    This project implements the base OWBaseWidget class and utilities for use
    in Orange Canvas workflows.

  doc_url: https://orange-widget-base.readthedocs.io/
  dev_url: https://github.com/biolab/orange-widget-base/

extra:
  recipe-maintainers:
    - ales-erjavec
    - lanzagar
    - markotoplak
    - primozgodec
